<?php

/**
 * Famille_mots_cleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Famille_mots_cleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Famille_mots_cleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Famille_mots_cle');
    }
}