<?php

/**
 * Mots_cleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mots_cleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mots_cleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mots_cle');
    }
}