<?php

/**
 * ReferenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReferenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReferenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reference');
    }
}