<?php

/**
 * RessourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RessourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RessourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ressource');
    }
}