<?php

/**
 * Type_ressourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Type_ressourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Type_ressourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type_ressource');
    }
}